services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    container_name: envoy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml:ro
    command: envoy -c /etc/envoy/envoy.yaml --log-level warn
    networks:
      - valhalla-proxy

networks:
  valhalla-proxy:
    name: valhalla-proxy
    driver: bridge
