services:
  traefik:
    image: traefik:v3.7.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /run/podman/podman.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - traefik-data:/data
    networks:
      - valhalla-proxy

networks:
  valhalla-proxy:
    name: valhalla-proxy
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

volumes:
  traefik-data:
